### ISSUE TITLE
[v2.12.0] Ensure CI/documentation reflect changes to default admin credentials

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/anomaly-detection#1120]
## Background
Previously, when installing the security plugin demo configuration, the cluster was spun up with the default admin credentials, `admin:admin`. A change was made in `main` and backported to `2.x` for the `2.12.0` release, which now requires an initial admin password to be passed in via the environment variable `OPENSEARCH_INITIAL_ADMIN_PASSWORD`. This will break some CI/testing that relies on OpenSearch to come up without setting this environment variable. This tracking issue is to ensure compliance with the new changes.

Coming from: https://github.com/opensearch-project/security/issues/3624

## Acceptance Criteria
 - [ ] All documentation references to the old default credentials `admin:admin` are removed
 - [ ] Ensure that CI/testing is working with `main` and `2.x` branches

**Comment by jackiehanyang** [comment]
> This will break some CI/testing that relies on OpenSearch to come up without setting this environment variable. 

We can signoff AD as AD 2.x branch had successful build after this issue is created - https://github.com/opensearch-project/anomaly-detection/actions/runs/7186078710/job/19570706034

However, there're two issues with AD 2.x branch build:
- gradle version not compatible with Java20 - https://github.com/opensearch-project/anomaly-detection/actions/runs/7186078710/job/19570706034
- non compatible jackson-core version - https://github.com/opensearch-project/anomaly-detection/actions/runs/7350161068/job/20550526202

The first issue can be resolved after this pr is merged - https://github.com/opensearch-project/anomaly-detection/pull/1132. Added a comment in this pr to include the jackson-core change here - https://github.com/opensearch-project/anomaly-detection/pull/1132#issuecomment-1904963959

**Comment by jackiehanyang** [comment]
opened pr to remove default credentials - https://github.com/opensearch-project/anomaly-detection/pull/1134
