### ISSUE TITLE
[BUG] 1.2.4 build failing due to missing org.apache.commons.lang3

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/anomaly-detection#359]
**Describe the bug**
The build for `1.2.4` fails due to missing `org.apache.commons.lang3` library.

**Other plugins installed**
This is being used as a part of [opensearch-1.2.4.yml](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.4/opensearch-1.2.4.yml)

**Error log**
[error.log](https://github.com/opensearch-project/anomaly-detection/files/7859269/error.log)

**Expected behavior**
The build is a success for 1.2.4

**Comment by amitgalitz** [comment]
We have had issues for lang3 dependency missing that we fixed with this PR (https://github.com/opensearch-project/anomaly-detection/pull/350) that was merged into our main branch. This was due to lang3 dependency being transitively removed form job-scheduler 1.3.0. I am not sure why this showed up for the 1.2.4 build suddenly and why we aren't seeing any issues building AD in our for 1.2.4 locally or in our workflows.
