### ISSUE TITLE
[BUG] Discrepancy between Profile API and realtime tasks API

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/anomaly-detection#502]
**What is the bug?**
There is discrepancy between the results returned from the profile API and search tasks API. This occurs when restarting an Opensearch cluster that already has a HCAD running. 
**How can one reproduce the bug?**
1.  Start Opensearch cluster and dashboards with AD plugin
2. create and wait for HCAD to be running and returning anomaly results
3. stop and start OpenSearch cluster
4. HCAD will go back to showing as initializing again on frontend
5. Profile API for detector will return response of `running`
6. Search request to `..._plugins/_anomaly_detection/detectors/tasks/_search` with body of:
```
{
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "detector_id": "N64oKYABE8ZUzJlQp33e"
          }
        },
        {
          "term": {
            "task_type": "REALTIME_HC_DETECTOR"
          }
        },
        {
          "term": {
            "is_latest": "true"
          }
        }
      ]
    }
  }
}
```
returns response with `initializing`

**What is the expected behavior?**
HCAD to show as `running` on frontend and all relevant API responses

**What is your host/environment?**
 - Opensearch 2.0.0-alpha1-snapshot (4/14/22)

**Comment by ylwu-amzn** [comment]
For HC detector:
- Realtime task calculate state&init_progress with RCF total updates, check https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java#L550-L556, If detector restarted, the RCF model cache will be cleaned, and detector will not execute until next job run. So the realtime task get 0 total updates and will show as `INIT`.

- Profile API will select AD result index to check if there are any result generated for detector to tell whether it passed initialization of not , check https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java#L451-L461, if detector passed initialization, it will generate some AD result and store in result index. When detector restarted, the AD result still in result index, so profile API can find some result and regard the state as `RUNNING`.

**Comment by kaituo** [comment]
I experienced it myself without restarting a node. My case is when the data runs out the HCAD detector status change to init. Will debug about this.

**Comment by kaituo** [comment]
Another case is when I have long interval detector (2hr). Hourly Cron cleared the real time task cache and we never update the state to running since the cache is always empty. The detector will stay init forever on the frontend.

**Comment by kaituo** [comment]
Proposed fix: to query the result index when the total updates is 0 like profile API. The pros are that the change is simple. The con is extra query. Considering the query is to get [1 result](https://github.com/opensearch-project/anomaly-detection/blob/7cefb143d61178223eec0dc1aa5aa2a16534316e/src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java#L618) instead of multiple results from result index. It is relatively cheap. It won't cause the frontend to wait longer as the query is initialized by the job scheduler run, not frontend. The frontend still reads states from task api 
```
GET _plugins/_anomaly_detection/detectors/<detectorId>?task=true
```

Alternative considered:
1. ignore the discrepancy. This will solve the restart problem that @amitgalitz mentioned, but not the case I mentioned. Also, the longer detector interval, the longer cx needs to wait to see the detector become running again.
2. remove hourly cron model cache reset. The cache reset clears unused memory and has been there since the first version of AD. We do not want to solve the state issue while ditching resource management.
3. Once the state becomes running, write logic that prevents the state from going back to init again. The con is that it does not solve the case I mentioned.

**Comment by kaituo** [comment]
One scenario that is not covered in https://github.com/opensearch-project/anomaly-detection/pull/753 is: what if there is no data left anymore? Without data, we won't trigger cold start and the detector will stay initialized until data appears again.
