### ISSUE TITLE
[BUG] search detector API doesn't recognize _source field 

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/anomaly-detection#669]
ml-commons is using the similar way to build search APIs and we received one bug https://github.com/opensearch-project/ml-commons/issues/419.

I guess AD has the same issue.  Refer to the ml-commons issue for more details of root cause.

Related AD code [AbstractSearchAction.java#L85](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/ad/rest/AbstractSearchAction.java#L85)

**Comment by amitgalitz** [comment]
For returning Anomaly Detector’s in our search response we have additional logic to re-parse our response into an `AnomalyDetector` object in-order to keep the correct order of the response after excluding the `ui_metdata`. When we add `_source` to exclude/include specific fields it changes the order of the response by default. Because we have implemented this logic, if we add the ability for example to exclude `timefield` than we will fail in re-parsing the detector object. 

The two ways to add the ability to use `_source ` is to write an additional `AnomalyDetetctor` parse method and find a non-redundant way to change `toXContent` to accommodate for the change while trying to keep the order or to stop caring about the order of the response body. 

I believe adding this capability is not important enough to change the order of our response, so for now I’ll split up the issue into two issues and first release a bug fix for other search API’s (anomaly results, detector tasks)

**Comment by ohltyler** [comment]
@amitgalitz I understand that we take the raw responses & parse into AnomalyDetector objs, but what does this have to do with persisting any order? Also, our API doesn't ensure that they will be returned in any particular order: https://opensearch.org/docs/latest/monitoring-plugins/ad/api/#search-detector

**Comment by kaituo** [comment]
@amitgalitz Can you forward port your changes to the main/3.0.0 branch?
